#
# Chipmunk2D Travis-CI Hook
#

# Travis language C++
language: cpp

install:
  - sudo apt-get install cmake >/dev/null 2>&1

script:
  - mkdir _build
  - cd _build
  - cmake ..
  - cmake --build . --config Release

# Execute additional tests or commands
#after_script:
#  - [run additional test commans]

# Only watch the master branch
branches:
  only:
    - binding

# Notify if needed
notifications:
  recipients:
    - codefoco@gmail.com

  email:
    on_success: change
    on_failure: always
